/ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2

    two_d_mode: true

    base_link_frame: "base_link"
    odom_frame: "odom"
    world_frame: "odom"
    publish_tf: false

    # ---------- LiDAR odom ----------
    odom0: "/odom_lidar"
    odom0_config: [
      true,  true,  false,   # x, y, z
      false, false, true,    # roll, pitch, yaw
      false, false, false,   # vx, vy, vz
      false, false, false,   # vroll, vpitch, vyaw
      false, false, false    # ax, ay, az
    ]
    odom0_differential: false
    odom0_relative: false

    # # ---------- IMU: use ONLY yaw rate (wz) ----------
    # imu0: "/livox/amr/imu"
    # imu0_config: [
    #   false, false, false,   # position
    #   false, false, false,   # orientation
    #   false, false, false,   # linear velocity
    #   false, false, true,    # angular velocity (wz only)
    #   false, false, false    # no linear acceleration
    # ]
    # imu0_differential: false
    # imu0_relative: false
    # imu0_remove_gravitational_acceleration: false
